allowBuilds:
  '@prisma/engines': true
  '@snaplet/seed': true
  sharp: true
  supabase: true

ignoredBuiltDependencies:
  - '@snaplet/seed'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - sharp
  - supabase
