ALTER TABLE public.llamados_atencion
  ADD COLUMN IF NOT EXISTS resuelto BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS fecha_resolucion TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS resuelto_por UUID;
